### ISSUE TITLE
Variable type column in variables.csv: "variableType" or "typeEnd"

### ISSUE THREAD

**Issue by JuanLiOHRI** [Big-Life-Lab/recodeflow#17]
The current variables.csv has one column for variable types, it's either called "variableType" (https://big-life-lab.github.io/cchsflow/articles/variables_sheet.html) or "typeEnd" (https://github.com/CBjerke/PREDIGT-model-parameters/blob/main/model-export/variables.csv): should we make it consistent across all files?

**Comment by yulric** [comment]
It should be `variableType`. `typeEnd` is only for the variable details CSV file.
